### ISSUE TITLE
O link "Download Now" baixa uma versão antiga.

### ISSUE THREAD

**Issue by felquis** [eduardolundgren/trackingjs.com#15]
O README.md vem vazio e não tem um LICENSE.md =s
https://github.com/downloads/eduardolundgren/tracking.js/tracking.js-1.0.0-alpha.zip

Esta correto?

**Comment by zenorocha** [comment]
Não está. Talvez seja melhor ao invés de linkar para um zip fechado, linkar para o zip com a última versão do master.
