### ISSUE TITLE
Duplicate menu

### ISSUE THREAD

**Issue by EduardoLopes** [eduardolundgren/trackingjs.com#30]
In the example's pages there's a link "tracking.js" in the title top bar, if i click, a duplicate menu appears.

Tried Chrome 36.0.1985.125 (Official Build 283153) and Firefox 31.0 on Ubuntu 12.04. 

Screenshot: [Imgur](http://i.imgur.com/p00wiGH.png)

**Comment by zenorocha** [comment]
Fixed in https://github.com/eduardolundgren/tracking.js/pull/83
